### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by CasketPizza** [ghlre/GHL_HIDEmulator#1]
Heya when i run this after following the instructions i get this before the window closes with the hardware removed sound:
`Frets:    00-win64>D:\clonehero-win64\GHL_HIDEmulator.exe
Buttons:  00ar Hero Live guitar!
Tilt:     00
Whammy:   80
Strum:    False
Raw Data: 00-00-0F-80-80-80-80-00-00-00-00-00-00-00-00-00-00-00-00-00-02-00-02-00-02-00-02

Unhandled Exception: Nefarius.ViGEm.Client.Targets.Xbox360.Exceptions.Xbox360UserIndexNotReportedException: Exception of type 'Nefarius.ViGEm.Client.Targets.Xbox360.Exceptions.Xbox360UserIndexNotReportedException' was thrown.
   at Nefarius.ViGEm.Client.Targets.Xbox360Controller.get_UserIndex()
   at GHL_HIDEmulator.Program.Main(String[] args)`

any help is greatly appreciated

**Comment by akadawn** [comment]
> Heya when i run this after following the instructions i get this before the window closes with the hardware removed sound:
> `Frets: 00-win64>D:\clonehero-win64\GHL_HIDEmulator.exe
> Buttons: 00ar Hero Live guitar!
> Tilt: 00
> Whammy: 80
> Strum: False
> Raw Data: 00-00-0F-80-80-80-80-00-00-00-00-00-00-00-00-00-00-00-00-00-02-00-02-00-02-00-02
> 
> Unhandled Exception: Nefarius.ViGEm.Client.Targets.Xbox360.Exceptions.Xbox360UserIndexNotReportedException: Exception of type 'Nefarius.ViGEm.Client.Targets.Xbox360.Exceptions.Xbox360UserIndexNotReportedException' was thrown.
> at Nefarius.ViGEm.Client.Targets.Xbox360Controller.get_UserIndex()
> at GHL_HIDEmulator.Program.Main(String[] args)`
> 
> any help is greatly appreciated

So basically after installing and uninstalling a few programs and spending about an hour going through stuff, i figured out that for the program to run it requires Clone Hero to already running, then you run the .exe file and it works as it should. Hope this helps :)
